version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: /venv/bin/python app.py
  
  test:
    build: .
    environment:
      - FLASK_ENV=testing
    command: /venv/bin/pytest tests/